
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state=JSON.parse(localStorage.getItem("ddSukigao9")||"null");
const blank=()=>({stage:"home",prelimScreens:[],prelimIndex:0,prelimChosen:[],prelimScores:{},mainCandidates:[],mainRound:0,mainScreens:[],mainIndex:0,mainScores:{},lastScreens:[],lastIndex:0,lastScores:{},finalists:[],finalPairs:[],finalIndex:0,finalWins:{},finalOrder:[]});
function save(){localStorage.setItem("ddSukigao9",JSON.stringify(state))}
function reset(){state=blank();save()}
function show(id){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");window.scrollTo({top:0,behavior:"smooth"});state.stage=id;save()}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function chunkRandom(arr,min=2,max=4){let a=shuffle(arr),out=[];while(a.length){if(a.length<=max){if(a.length<min&&out.length){let need=min-a.length;while(need--){let prev=out[out.length-1];a.push(prev.pop())}}out.push(a.splice(0,max));continue}let n=Math.floor(Math.random()*(max-min+1))+min;if(a.length-n===1)n--;out.push(a.splice(0,n))}return out.filter(x=>x.length)}
function m(id){return MEMBERS.find(x=>x.id===id)}
function cardHTML(x,extra=""){return `<div class="card ${extra}" data-id="${x.id}"><div class="photo">${`<img src="${x.image}" alt="" onerror="this.remove()">`}<span class="fallback">${x.name.slice(0,1)}</span></div><div class="check">✓</div><div class="card-body"><div class="name">${x.name}</div><div class="group">${GROUPS[x.group]}</div></div></div>`}
function attachFallback(){ $$(".photo").forEach(p=>{const img=p.querySelector("img"),f=p.querySelector(".fallback");if(img&&!img.complete)img.addEventListener("load",()=>f.style.display="none");else if(img&&img.naturalWidth)f.style.display="none"})}
function start(){reset();state.prelimScreens=chunkRandom(MEMBERS.map(x=>x.id));state.prelimChosen=[];state.prelimScores={};renderPrelim();show("prelim")}
function renderPrelim(){
 const s=state.prelimScreens[state.prelimIndex];$("#prelimCounter").textContent=`予選 ${state.prelimIndex+1} / ${state.prelimScreens.length}`;$("#prelimProgress").style.width=((state.prelimIndex)/state.prelimScreens.length*100)+"%";
 $("#prelimGrid").innerHTML=s.map(id=>cardHTML(m(id),state.prelimChosen.includes(id)?"selected":"")).join("");attachFallback();
 $$("#prelimGrid .card").forEach(c=>c.onclick=()=>{const id=c.dataset.id;if(state.prelimChosen.includes(id)){state.prelimChosen=state.prelimChosen.filter(x=>x!==id);c.classList.remove("selected")}else{state.prelimChosen.push(id);c.classList.add("selected");}$("#selectedCount").textContent=`選択中 ${state.prelimChosen.length}人`});
 $("#selectedCount").textContent=`選択中 ${state.prelimChosen.length}人`;
}
function prelimNext(){const s=state.prelimScreens[state.prelimIndex];if(state.prelimChosen.length===0){alert("少なくとも1人選んでね♡");return}state.prelimChosen.forEach(id=>state.prelimScores[id]=(state.prelimScores[id]||0)+1);state.prelimIndex++;if(state.prelimIndex<state.prelimScreens.length){state.prelimChosen=[];save();renderPrelim()}else finishPrelim()}
function finishPrelim(){let ids=MEMBERS.map(x=>x.id).filter(id=>state.prelimScores[id]);ids.sort((a,b)=>(state.prelimScores[b]||0)-(state.prelimScores[a]||0)||Math.random()-.5);state.mainCandidates=ids.slice(0,Math.min(18,ids.length));$("#prelimResultText").textContent=`予選で ${ids.length}人を選びました。上位 ${state.mainCandidates.length}人が本選へ進みます。`;$("#prelimStat").innerHTML=`本選進出：<b>${state.mainCandidates.length}人</b><br>予選では顔だけを見て直感で選んだ結果をもとに候補を絞ります。`;save();show("prelimClear")}
function setupMain(){state.mainRound=0;state.mainScores={};nextMainRound()}
function nextMainRound(){state.mainIndex=0;state.mainScreens=chunkRandom(state.mainCandidates,2,4);if(state.mainRound>=3){setupLast();return}renderMain();show("main")}
function renderMain(){const s=state.mainScreens[state.mainIndex];$("#mainRoundLabel").textContent=`ROUND ${state.mainRound+1} / 3`;$("#mainCounter").textContent=`${state.mainIndex+1} / ${state.mainScreens.length}`;$("#mainProgress").style.width=((state.mainIndex)/state.mainScreens.length*100)+"%";$("#mainQuestion").textContent="① 一番好きな顔は？";$("#mainHint").textContent="まず1位をタップ";$("#mainGrid").innerHTML=s.map(id=>cardHTML(m(id))).join("");attachFallback();$$("#mainGrid .card").forEach(c=>c.onclick=()=>mainPick(c.dataset.id))}
let mainFirst=null;
function mainPick(id){if(!mainFirst){mainFirst=id;$("#mainQuestion").textContent="② 次に好きな顔は？";$("#mainHint").textContent="2位をタップ";$$("#mainGrid .card").forEach(c=>c.classList.toggle("selected",c.dataset.id===id));return}if(id===mainFirst){return}state.mainScores[mainFirst]=(state.mainScores[mainFirst]||0)+3;state.mainScores[id]=(state.mainScores[id]||0)+1;mainFirst=null;state.mainIndex++;if(state.mainIndex<state.mainScreens.length){save();renderMain()}else{state.mainRound++;save();nextMainRound()}}
function setupLast(){let all=state.mainCandidates.slice();all.sort((a,b)=>(state.mainScores[b]||0)-(state.mainScores[a]||0)||Math.random()-.5);state.lastScreens=chunkRandom(all.slice(0,Math.min(12,all.length)),2,4);state.lastIndex=0;state.lastScores={};save();show("lastIntro")}
function renderLast(){let s=state.lastScreens[state.lastIndex];$("#lastCounter").textContent=`最終戦 ${state.lastIndex+1} / ${state.lastScreens.length}`;$("#lastProgress").style.width=((state.lastIndex)/state.lastScreens.length*100)+"%";$("#lastGrid").innerHTML=s.map(id=>cardHTML(m(id))).join("");attachFallback();$$("#lastGrid .card").forEach(c=>c.onclick=()=>lastPick(c.dataset.id))}
let lastFirst=null;
function lastPick(id){if(!lastFirst){lastFirst=id;$("#lastGrid .card").forEach?.(()=>{});$("#lastGrid .card").forEach(c=>c.classList.toggle("selected",c.dataset.id===id));return}if(id===lastFirst)return;state.lastScores[lastFirst]=(state.lastScores[lastFirst]||0)+3;state.lastScores[id]=(state.lastScores[id]||0)+1;lastFirst=null;state.lastIndex++;if(state.lastIndex<state.lastScreens.length){save();renderLast()}else finishLast()}
function finishLast(){let combined=state.mainCandidates.map(id=>[id,(state.mainScores[id]||0)+(state.lastScores[id]||0)]);combined.sort((a,b)=>b[1]-a[1]||Math.random()-.5);state.finalists=combined.slice(0,Math.min(18,combined.length)).map(x=>x[0]);$("#finalistStat").innerHTML=`決勝進出：<b>${state.finalists.length}人</b><br>ここから完全二択でTOP9を決めます。`;save();show("finalIntro")}
function makePairs(){let a=shuffle(state.finalists);let pairs=[];for(let i=0;i<a.length-1;i+=2)pairs.push([a[i],a[i+1]]);return pairs}
function startFinal(){state.finalRound=0;state.finalPairs=[];state.finalIndex=0;state.finalWins={};state.finalOrder=[];nextFinalRound()}
function nextFinalRound(){if(state.finalRound>=4){finishFinal();return}state.finalPairs=makePairs();state.finalIndex=0;save();renderFinal();show("final")}
function renderFinal(){let p=state.finalPairs[state.finalIndex];$("#finalCounter").textContent=`ROUND ${state.finalRound+1} / 4　比較 ${state.finalIndex+1} / ${state.finalPairs.length}`;$("#finalProgress").style.width=(state.finalIndex/state.finalPairs.length*100)+"%";$("#finalDuel").innerHTML=p.map(id=>cardHTML(m(id))).join("");attachFallback();$$("#finalDuel .card").forEach(c=>c.onclick=()=>finalPick(c.dataset.id))}
function finalPick(id){state.finalWins[id]=(state.finalWins[id]||0)+1;state.finalIndex++;if(state.finalIndex<state.finalPairs.length){save();renderFinal()}else{state.finalRound++;save();nextFinalRound()}}
function finishFinal(){let scores={};state.finalists.forEach(id=>scores[id]=state.finalWins[id]||0);let sorted=state.finalists.slice().sort((a,b)=>(scores[b]-scores[a])||Math.random()-.5);state.finalOrder=sorted.slice(0,9);save();renderResult();show("result")}
function renderResult(){let medals=["🥇","🥈","🥉"];$("#ranking").innerHTML=state.finalOrder.map((id,i)=>{let x=m(id);return `<div class="rank"><div class="ranknum">${medals[i]||i+1}</div><div class="rankphoto"><img src="${x.image}" alt="" onerror="this.remove()"><span>${x.name.slice(0,1)}</span></div><div><div class="rankname">${x.name}</div><div class="rankgroup">${GROUPS[x.group]}</div></div></div>`}).join("");}
function copyResult(){const t="株式会社DD 好き顔9選\\n"+state.finalOrder.map((id,i)=>`${i+1}位 ${m(id).name}`).join("\\n");navigator.clipboard?.writeText(t).then(()=>alert("結果をコピーしました！")).catch(()=>prompt("コピーしてね",t))}
$("#startBtn").onclick=start;$("#resumeBtn").onclick=()=>{if(state?.stage==="prelim"){renderPrelim();show("prelim")}else if(state?.stage==="main"){renderMain();show("main")}else if(state?.stage==="last"){renderLast();show("last")}else if(state?.stage==="final"){renderFinal();show("final")}else show("home")};
$("#prelimNext").onclick=prelimNext;$("#prelimBack").onclick=()=>{if(state.prelimIndex>0){state.prelimIndex--;state.prelimChosen=[];renderPrelim()}};
$("#mainIntroBtn").onclick=()=>{setupMain();show("main")};$("#retryBtn").onclick=start;$("#mainStartBtn").onclick=()=>{setupMain();show("main")};
$("#lastStartBtn").onclick=()=>{renderLast();show("last")};$("#finalStartBtn").onclick=startFinal;$("#copyBtn").onclick=copyResult;$("#restartBtn").onclick=start;$("#topBtn").onclick=()=>show("home");
window.addEventListener("load",()=>{if(state&&state.stage&&state.stage!=="home")$("#resumeBtn").hidden=false});
